const SHEET_ID="1_Rk6A00FDx8ZFAdhRshI9-klzB2Nq9MOWJ4AYFObpIo";
const SHEET_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq`;
const DAYS=["fri","sat","sun"], DAY_LABEL={fri:"Friday",sat:"Saturday",sun:"Sunday"}, DAY_DATE={fri:"July 10, 2026",sat:"July 11, 2026",sun:"July 12, 2026"};
const SHIFT_ORDER=["shift1","morningsession","shift2","shift3","afternoonsession","shift4"], SHIFT_TIMELINE=["shift1","morningsession","shift2","shift3","afternoonsession","shift4"];
const TIMELINE_INDEX=Object.fromEntries(SHIFT_TIMELINE.map((s,i)=>[s,i]));
const SHIFT_LABEL={shift1:"8:20am - Opening Song (Morning)",morningsession:"Morning Session",shift2:"Closing Song (Morning) - 12:55pm",shift3:"12:55pm - Opening Song (Afternoon)",afternoonsession:"Afternoon Session",shift4:"Closing Song (Afternoon) - End"};
const SHIFT_CONFLICT={shift1:"shift1",morningsession:"shift1",shift2:"shift23",shift3:"shift23",afternoonsession:"shift4counters",shift4:"shift4counters"};
const CONFLICT_COLS=[["fri","shift1"],["fri","shift23"],["fri","shift4counters"],["sat","shift1"],["sat","shift23"],["sat","shift4counters"],["sun","shift1"],["sun","shift23"],["sun","shift4counters"]];
const SESSION_BOXES=[8,9,10], FULL_BOXES=[1,2,3,4,5,6,7,8,9,10], NUM_BROTHERS=2, NUM_COUNTERS=8;
const SPECIAL_ROLES={"Dale Lao Flores":"Counting Overseer","Gomer Dohiling":"Box Overseer","Ruel Ryan Rosal":"Accounts Overseer"};
const EXCLUDED=new Set(Object.keys(SPECIAL_ROLES)), RESTRICTED_TO_COUNTERS=new Set(["Jaye Kayla Rosal"]);
let activeDay="fri", VOLUNTEER_NAMES=[];
function norm(v){return String(v||"").replace(/\s+/g," ").trim()} function low(v){return norm(v).toLowerCase()}
function cv(c){return !c||c.v==null?"":String(c.v).trim()}
async function fetchSheet(sheet){const p=new URLSearchParams({sheet,tqx:"out:json"});const r=await fetch(`${SHEET_URL}?${p}`,{cache:"no-store"});if(!r.ok)throw new Error(`${sheet}: HTTP ${r.status}`);let t=await r.text();t=t.replace(/^\/\*O_o\*\/\s*/,"").replace(/^google\.visualization\.Query\.setResponse\(/,"").replace(/\);?\s*$/,"");const j=JSON.parse(t);if(j.status!=="ok")throw new Error(`${sheet}: GViz error`);return j.table.rows.map(row=>row.c.map(cv))}
function parseVolunteers(rows){const seen=new Set(), out=[];for(const row of rows){const no=norm(row[1]), messenger=norm(row[2]), realName=norm(row[3]), role=norm(row[4]);if(!/^\d+$/.test(no)||!realName||!role||seen.has(realName))continue;seen.add(realName);out.push({no:+no,messenger,realName,role})}return out}
function parseConflicts(rows,messengerToReal){const conflicts=new Map();const add=(d,k,n)=>{const key=`${d}|${k}`;if(!conflicts.has(key))conflicts.set(key,new Set());conflicts.get(key).add(n)};for(const row of rows){CONFLICT_COLS.forEach(([d,k],i)=>{const raw=norm(row[i]);if(!raw)return;add(d,k,messengerToReal.get(raw)||raw)})}return conflicts}
function getSet(conflicts,d,k){return conflicts.get(`${d}|${k}`)||new Set()}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0)/4294967296}
function shiftsOverlap(a,b){if(a==="counter")return ["shift3","afternoonsession","shift4"].includes(b);if(b==="counter")return ["shift3","afternoonsession","shift4"].includes(a);return a in TIMELINE_INDEX&&b in TIMELINE_INDEX&&Math.abs(TIMELINE_INDEX[a]-TIMELINE_INDEX[b])<=1}
function roleScore(roleHistory,rn,day,newRole){const hist=roleHistory.get(rn)||new Map(), all=new Set();for(const roles of hist.values())for(const r of roles)all.add(r);if(!all.has(newRole))return 4;if(hist.get(day)&&hist.get(day).has(newRole))return -4;return -1}
function buildSchedule(volunteers,conflictRows){const messengerToReal=new Map(volunteers.map(v=>[v.messenger,v.realName]));const roleByName=new Map(volunteers.map(v=>[v.realName,v.role]));Object.keys(SPECIAL_ROLES).forEach(n=>roleByName.set(n,"Brother"));const conflicts=parseConflicts(conflictRows,messengerToReal), brothers=volunteers.filter(v=>v.role==="Brother"), sisters=volunteers.filter(v=>v.role==="Sister");
const assignmentCount=new Map(), roleHistory=new Map(), assignedPerDay=new Map(), allAssignments=new Map();
const canWork=(rn,d,k)=>!EXCLUDED.has(rn)&&!getSet(conflicts,d,k).has(rn);const existing=(d,rn)=>assignedPerDay.get(`${d}|${rn}`)||[];const canAdd=(d,rn,s)=>existing(d,rn).length<2&&!existing(d,rn).some(x=>shiftsOverlap(x,s));
const recDay=(d,rn,s)=>{const key=`${d}|${rn}`;if(!assignedPerDay.has(key))assignedPerDay.set(key,[]);assignedPerDay.get(key).push(s)};
const recRole=(rn,d,role)=>{if(!roleHistory.has(rn))roleHistory.set(rn,new Map());if(!roleHistory.get(rn).has(d))roleHistory.get(rn).set(d,new Set());roleHistory.get(rn).get(d).add(role)};
const recAssign=(rn,d,s,role)=>{if(!allAssignments.has(rn))allAssignments.set(rn,[]);allAssignments.get(rn).push({day:d,shiftKey:s,roleCat:role});assignmentCount.set(rn,(assignmentCount.get(rn)||0)+1);recRole(rn,d,role)};
const sorter=(d,s,role)=>(a,b)=>{const av=roleScore(roleHistory,a.realName,d,role)-(assignmentCount.get(a.realName)||0)*.7-existing(d,a.realName).length*1.5+hash(`${d}|${s}|${a.realName}`);const bv=roleScore(roleHistory,b.realName,d,role)-(assignmentCount.get(b.realName)||0)*.7-existing(d,b.realName).length*1.5+hash(`${d}|${s}|${b.realName}`);return bv-av};
const assign=(d,s,pool,count,role,extra=[])=>{const keys=[SHIFT_CONFLICT[s],...extra];const chosen=pool.filter(p=>!RESTRICTED_TO_COUNTERS.has(p.realName)).filter(p=>keys.every(k=>canWork(p.realName,d,k))).filter(p=>canAdd(d,p.realName,s)).sort(sorter(d,s,role)).slice(0,count).map(p=>p.realName);chosen.forEach(rn=>recAssign(rn,d,s,role));return chosen};
const counters=(d)=>{const avail=volunteers.filter(v=>!EXCLUDED.has(v.realName)&&canWork(v.realName,d,"shift4counters")&&canAdd(d,v.realName,"counter"));const sel=[];const push=p=>{if(p&&!sel.some(x=>x.realName===p.realName))sel.push(p)};push(avail.find(v=>v.realName==="Jaye Kayla Rosal"));const bros=avail.filter(v=>v.role==="Brother").sort(sorter(d,"counter","counter")), sis=avail.filter(v=>v.role==="Sister"&&v.realName!=="Jaye Kayla Rosal").sort(sorter(d,"counter","counter"));bros.slice(0,Math.min(4,Math.max(2,bros.length))).forEach(push);sis.forEach(p=>{if(sel.length<NUM_COUNTERS)push(p)});bros.forEach(p=>{if(sel.length<NUM_COUNTERS)push(p)});const out=sel.slice(0,NUM_COUNTERS).map(p=>p.realName);out.forEach(rn=>{recAssign(rn,d,"counter","counter");recDay(d,rn,"counter")});return out};
const schedule={};for(const d of DAYS){schedule[d]={};let sh1=[],sh3=[];for(const s of ["shift1","morningsession","shift2","shift3","afternoonsession"]){let bros;if(s==="morningsession")bros=sh1;else if(s==="afternoonsession")bros=sh3;else{bros=assign(d,s,brothers,NUM_BROTHERS,"brother",s==="shift3"?["shift4counters"]:[]);bros.forEach(rn=>recDay(d,rn,s));if(s==="shift1")sh1=[...bros];if(s==="shift3")sh3=[...bros]}const boxCount=["morningsession","afternoonsession"].includes(s)?SESSION_BOXES.length:FULL_BOXES.length;const boxes=assign(d,s,sisters,boxCount,"box");boxes.forEach(rn=>recDay(d,rn,s));schedule[d][s]={brothers:bros,boxes}}const c=counters(d);const b4=assign(d,"shift4",brothers,NUM_BROTHERS,"brother");b4.forEach(rn=>recDay(d,rn,"shift4"));const bx4=assign(d,"shift4",sisters,FULL_BOXES.length,"box");bx4.forEach(rn=>recDay(d,rn,"shift4"));schedule[d].shift4={brothers:b4,boxes:bx4,counters:c}}
return {schedule,volunteers,conflicts,roleByName,assignedPerDay,allAssignments,canWork}}

function splitNames(value){return norm(value).split(/[\n,;]+/).map(norm).filter(Boolean)}
function parseDay(value){const v=low(value);if(v.startsWith("fri"))return "fri";if(v.startsWith("sat"))return "sat";if(v.startsWith("sun"))return "sun";return ""}
function parseShift(value){const v=low(value).replace(/[^a-z0-9]+/g,"");if(v==="1"||v.includes("shift1")||v.includes("opening")&&v.includes("morning"))return "shift1";if(v.includes("morningsession"))return "morningsession";if(v==="2"||v.includes("shift2")||v.includes("closing")&&v.includes("morning"))return "shift2";if(v==="3"||v.includes("shift3")||v.includes("opening")&&v.includes("afternoon"))return "shift3";if(v.includes("afternoonsession"))return "afternoonsession";if(v==="4"||v.includes("shift4")||v.includes("closing")&&v.includes("afternoon"))return "shift4";return ""}
function roleKind(value){const v=low(value);if(v.includes("counter"))return "counter";if(v.includes("brother")||v.includes("key"))return "brother";if(v.includes("box")||v.includes("attendant")||v.includes("sister"))return "box";return ""}
function resolvePersonName(raw,messengerToReal,realLookup){const n=norm(raw);if(!n)return "";return realLookup.get(low(n))||messengerToReal.get(n)||n}
function emptySchedule(){const schedule={};for(const d of DAYS){schedule[d]={};for(const s of SHIFT_ORDER)schedule[d][s]={brothers:[],boxes:[]};schedule[d].shift4.counters=[]}return schedule}
function buildFromAssignments(volunteers,conflictRows,assignmentRows){const messengerToReal=new Map(volunteers.map(v=>[v.messenger,v.realName]));const realLookup=new Map(volunteers.map(v=>[low(v.realName),v.realName]));const roleByName=new Map(volunteers.map(v=>[v.realName,v.role]));Object.keys(SPECIAL_ROLES).forEach(n=>roleByName.set(n,"Brother"));const conflicts=parseConflicts(conflictRows,messengerToReal), schedule=emptySchedule(), assignedPerDay=new Map(), allAssignments=new Map();
const canWork=(rn,d,k)=>!EXCLUDED.has(rn)&&!getSet(conflicts,d,k).has(rn);const rec=(rn,d,s,role,trackDay=true)=>{if(!allAssignments.has(rn))allAssignments.set(rn,[]);allAssignments.get(rn).push({day:d,shiftKey:s,roleCat:role});if(!trackDay)return;const key=`${d}|${rn}`;if(!assignedPerDay.has(key))assignedPerDay.set(key,[]);assignedPerDay.get(key).push(s)};
let rows=assignmentRows.filter(r=>r.some(c=>norm(c)));if(!rows.length)return null;let header=rows[0].map(low);const hasHeader=header.some(h=>["day","date","shift","role","name","realname","volunteer","keybrothers"].includes(h)||h.startsWith("box"));if(!hasHeader){header=[]}else rows=rows.slice(1);
const idx=name=>header.findIndex(h=>h===name||h.replace(/\s+/g,"")===name);const dayIdx=Math.max(idx("day"),idx("date")), shiftIdx=idx("shift"), roleIdx=idx("role"), nameIdx=Math.max(idx("name"),idx("realname"),idx("volunteer"),idx("volunteername")), boxIdx=idx("box");
let used=0;
if(dayIdx>=0&&shiftIdx>=0&&nameIdx>=0){for(const row of rows){const d=parseDay(row[dayIdx]), s=parseShift(row[shiftIdx]), rk=roleKind(row[roleIdx]||"");if(!d||!s)continue;for(const raw of splitNames(row[nameIdx])){const rn=resolvePersonName(raw,messengerToReal,realLookup);if(!rn)continue;if(rk==="counter"){schedule[d].shift4.counters.push(rn);rec(rn,d,"counter","counter")}else if(rk==="brother"){schedule[d][s].brothers.push(rn);rec(rn,d,s,"brother",!["morningsession","afternoonsession"].includes(s))}else{schedule[d][s].boxes.push(rn);rec(rn,d,s,"box")}used++}}}
else if(dayIdx>=0&&shiftIdx>=0){const keyIdx=header.findIndex(h=>h.includes("key")||h.includes("brother"));const counterIdx=header.findIndex(h=>h.includes("counter"));const boxIdxs=header.map((h,i)=>h.startsWith("box")?i:-1).filter(i=>i>=0);for(const row of rows){const d=parseDay(row[dayIdx]), s=parseShift(row[shiftIdx]);if(!d||!s)continue;if(keyIdx>=0)for(const raw of splitNames(row[keyIdx])){const rn=resolvePersonName(raw,messengerToReal,realLookup);schedule[d][s].brothers.push(rn);rec(rn,d,s,"brother",!["morningsession","afternoonsession"].includes(s));used++}for(const i of boxIdxs)for(const raw of splitNames(row[i])){const rn=resolvePersonName(raw,messengerToReal,realLookup);schedule[d][s].boxes.push(rn);rec(rn,d,s,"box");used++}if(counterIdx>=0)for(const raw of splitNames(row[counterIdx])){const rn=resolvePersonName(raw,messengerToReal,realLookup);schedule[d].shift4.counters.push(rn);rec(rn,d,"counter","counter");used++}}}
if(!used)return null;for(const d of DAYS)for(const s of SHIFT_ORDER){schedule[d][s].brothers=[...new Set(schedule[d][s].brothers)];schedule[d][s].boxes=[...new Set(schedule[d][s].boxes)]}for(const d of DAYS)schedule[d].shift4.counters=[...new Set(schedule[d].shift4.counters)];return {schedule,volunteers,conflicts,roleByName,assignedPerDay,allAssignments,canWork,source:"Assignments"}}

function esc(str){if(typeof document==="undefined")return String(str).replace(/[&<>"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[ch]));const d=document.createElement("div");d.textContent=str;return d.innerHTML}
function rclass(n,roleByName){return roleByName.get(n)==="Sister"?"sister-tag":"brother-tag"} function tag(n,roleByName){return `<span class="name-tag ${rclass(n,roleByName)}">${esc(n)}</span>`}
function boxHtml(names,roleByName,isSession){const nums=isSession?SESSION_BOXES:FULL_BOXES;return `<div class="box-grid">${nums.map((num,i)=>`<div class="box-row"><span class="box-num">${num}</span>${tag(names[i]||"TBD",roleByName)}</div>`).join("")}</div>`}
function card(day,s,data,roleByName){const sess=["morningsession","afternoonsession"].includes(s), all=[...data.brothers,...data.boxes,...(data.counters||[])], names=all.map(low).join(" ");const ctr=data.counters?`<div class="role-section" style="margin-top:16px"><h4>Counters</h4><div class="name-list">${data.counters.map(n=>tag(n,roleByName)).join("")}</div></div>`:"";return `<div class="shift-card" data-names="${esc(names)}" data-day="${day}" data-shift="${s}"><div class="shift-header"><span class="shift-time"><span class="shift-num">${SHIFT_ORDER.indexOf(s)+1}</span>${esc(SHIFT_LABEL[s])}</span></div><div class="shift-body-grid"><div class="role-section"><h4>Key Brothers</h4><div class="name-list">${data.brothers.map(n=>tag(n,roleByName)).join("")}</div></div><div class="role-section"><h4>Box Attendants${sess?" · Boxes 8-10":""}</h4>${boxHtml(data.boxes,roleByName,sess)}${ctr}</div></div></div>`}
function renderSchedule(state){for(const d of DAYS){document.getElementById(`day-${d}`).innerHTML=`<div class="section-title">${DAY_LABEL[d]} &mdash; ${DAY_DATE[d]}</div>`+SHIFT_ORDER.map(s=>card(d,s,state.schedule[d][s],state.roleByName)).join("\n")}const names=Object.keys(SPECIAL_ROLES), special=document.getElementById("oversight-section");special.setAttribute("data-names",names.map(low).join(" "));special.innerHTML=`<h2 class="section-title">Oversight</h2><p class="section-desc">Department oversight across all three days</p><div class="special-roles-grid">${names.map(n=>`<div class="special-role-item">${tag(n,state.roleByName)} <span class="special-role-desc">&mdash; ${esc(SPECIAL_ROLES[n])}</span></div>`).join("")}</div>`;VOLUNTEER_NAMES=[...state.volunteers.map(v=>v.realName),...names].sort((a,b)=>a.localeCompare(b))}
function validateSchedule(state){const errs=[];for(const d of DAYS)for(const s of SHIFT_ORDER){const data=state.schedule[d][s], expected=["morningsession","afternoonsession"].includes(s)?3:10;if(data.brothers.length!==2)errs.push(`${d}/${s}: brothers ${data.brothers.length}`);if(data.boxes.length!==expected)errs.push(`${d}/${s}: boxes ${data.boxes.length}`);[...data.brothers,...data.boxes].forEach(n=>{if(!state.canWork(n,d,SHIFT_CONFLICT[s]))errs.push(`${n} conflicts ${d}/${s}`)});if(s==="shift4"){if((data.counters||[]).length!==8)errs.push(`${d}/counters: ${(data.counters||[]).length}`);(data.counters||[]).forEach(n=>{if(!state.canWork(n,d,"shift4counters"))errs.push(`${n} conflicts ${d}/counters`)})}}for(const [key,shifts] of state.assignedPerDay.entries())for(let i=0;i<shifts.length;i++)for(let j=i+1;j<shifts.length;j++)if(shiftsOverlap(shifts[i],shifts[j]))errs.push(`${key}: ${shifts[i]} + ${shifts[j]}`);return errs}
async function loadSourceData(){const [vRows,cRows,aRows]=await Promise.all([fetchSheet("Volunteer List"),fetchSheet("Schedule conflict"),fetchSheet("Assignments").catch(()=>[])]);const volunteers=parseVolunteers(vRows);const fromAssignments=buildFromAssignments(volunteers,cRows,aRows);return fromAssignments||{...buildSchedule(volunteers,cRows),source:"generated"}}
async function initDynamicSchedule(){const status=document.getElementById("searchStatus");try{status.textContent="Loading live schedule from Google Sheets…";const state=await loadSourceData(), errs=validateSchedule(state);if(errs.length){console.warn("Schedule validation warnings",errs);status.textContent=`Loaded ${state.source==="Assignments"?"from Assignments tab":"from generated sheet data"} with ${errs.length} validation warning(s).`}else status.textContent=state.source==="Assignments"?"Loaded live from the Assignments tab.":"Assignments tab is empty, so a live schedule was generated from Volunteer List + Schedule conflict.";renderSchedule(state);showDay(activeDay);setTimeout(()=>{if(!document.getElementById("searchInput").value.trim())status.textContent=""},2500)}catch(e){console.error(e);status.innerHTML=`Could not load Google Sheet data: <strong>${esc(e.message)}</strong>`}}
function showDay(day){activeDay=day;document.querySelectorAll(".day-panel").forEach(p=>p.classList.remove("active"));const p=document.getElementById(`day-${day}`);if(p)p.classList.add("active");document.querySelectorAll(".tab-btn").forEach(btn=>{const a=btn.getAttribute("data-day")===day;btn.classList.toggle("tab-active",a);btn.setAttribute("aria-selected",a?"true":"false")})}
function searchNames(){const input=document.getElementById("searchInput"), status=document.getElementById("searchStatus"), clear=document.getElementById("searchClear"), heading=document.getElementById("searchResultName"), display=document.getElementById("searchNameDisplay"), filter=low(input.value), sections=document.querySelectorAll(".shift-card, .special-roles-section");document.querySelectorAll(".name-tag").forEach(t=>t.classList.remove("name-hit"));clear.classList.toggle("visible",!!filter);if(!filter){sections.forEach(el=>el.classList.remove("filtered-out","highlighted"));status.textContent="";heading.classList.remove("visible");return}const exact=VOLUNTEER_NAMES.find(n=>low(n)===filter);if(exact){display.textContent=exact;heading.classList.add("visible")}else heading.classList.remove("visible");document.querySelectorAll(".name-tag").forEach(t=>{if(low(t.textContent).includes(filter))t.classList.add("name-hit")});const dayMatches={fri:0,sat:0,sun:0};let count=0;sections.forEach(el=>{const names=(el.getAttribute("data-names")||"").toLowerCase();if(names.includes(filter)){el.classList.remove("filtered-out");el.classList.add("highlighted");count++;const par=el.closest(".day-panel");if(par&&par.id.startsWith("day-"))dayMatches[par.id.replace("day-","")]++;else DAYS.forEach(d=>dayMatches[d]++)}else{el.classList.add("filtered-out");el.classList.remove("highlighted")}});if(count){const best=Object.entries(dayMatches).sort((a,b)=>b[1]-a[1])[0][0];if(best!==activeDay)showDay(best);status.innerHTML=`Showing <strong>${count}</strong> section(s) for "<strong>${esc(filter)}</strong>" <span class="clear-link" onclick="clearSearch()">Show all</span>`}else status.innerHTML=`No sections found for "<strong>${esc(filter)}</strong>" <span class="clear-link" onclick="clearSearch()">Clear</span>`}
function clearSearch(){document.getElementById("searchInput").value="";document.getElementById("searchResultName").classList.remove("visible");searchNames();document.getElementById("searchInput").focus()}
if(typeof document!=="undefined")document.addEventListener("DOMContentLoaded",initDynamicSchedule);if(typeof window!=="undefined"){window.showDay=showDay;window.searchNames=searchNames;window.clearSearch=clearSearch;window.__accountsSchedule={loadSourceData,validateSchedule}}if(typeof module!=="undefined")module.exports={loadSourceData,validateSchedule,parseVolunteers,buildSchedule,buildFromAssignments,fetchSheet};
